name = "mingqing-detector"
main = ".open-next/worker.js"
compatibility_date = "2026-05-02"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "mingqing-detector"
database_id = "b4efd9c5-e0e4-4b84-b8d9-70a89671bb5d"
