// Generated by scripts/generate-lite-bank-data.ts — run: npm run generate:lite-bank（或 generate:lite-bank:check）

import type { LiteBankEntry } from "../lib/lite-bank-types";

export const LITE_BANK_CORE_EXTREME: readonly LiteBankEntry[] = [
  {
    "id": "E001",
    "kind": "core-extreme",
    "stem": "朱元璋正税低,导致明朝官员腐败摊派严重,是洪武型孱弱的根源",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E002",
    "kind": "core-extreme",
    "stem": "大明宝钞是第一款成功发行且没有贬值的信用货币。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E003",
    "kind": "core-extreme",
    "stem": "美元发行后币值稳定了100多年,宋元纸币发行后稳定了20年,大明宝钞贬值比美元和宋元纸币慢。",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E004",
    "kind": "core-extreme",
    "stem": "大明宝钞发行失败的原因应该向宋金元探寻,而不是责怪朱元璋.",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E005",
    "kind": "core-extreme",
    "stem": "大明宝钞失败主要是后人执行坏、商民不配合；用宝钞问题批评洪武货币制度，本质上是在黑朱元璋。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E006",
    "kind": "core-extreme",
    "stem": "禁钱、禁金银,禁以物易物,必须使用宝钞,是宋元时期贵金属外流下的稳定货币秩序的必要手段；",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E007",
    "kind": "core-extreme",
    "stem": "明代白银化就是民间市场自然选择出来的进步，说明明朝商品经济前所未有的活跃。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E008",
    "kind": "core-extreme",
    "stem": "云南长期用贝、基层小额通货不足这类材料，地方长期民俗问题，不能拿来讨论明代货币治理能力差。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E009",
    "kind": "core-extreme",
    "stem": "清代从幕府进口铜矿,说明清代在铜钱流通重整上不可能做得比明代有效.说清朝铜币管理好的是满遗.",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E010",
    "kind": "core-extreme",
    "stem": "辽饷、名册发饷和冒饷争议主要就是明末官僚腐败和前线乱象，没必要上升到对洪武型分布式财政的批判。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E011",
    "kind": "core-extreme",
    "stem": "专款专用、钱粮直解各部是防止乱花钱的好制度",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E012",
    "kind": "core-extreme",
    "stem": "卫所军户和军屯是低成本养兵的制度智慧；后期坏掉只能怪军官侵占和地方腐败，不能追究制度设计者朱元璋。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E013",
    "kind": "core-extreme",
    "stem": "应该放弃锦州,抛弃朝鲜和蒙古,退守宁远,对于崇祯朝朝来说更有利",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E014",
    "kind": "core-extreme",
    "stem": "大航海时代，明朝错失了全球化先机,是因为朱元璋海禁和永乐废海改漕。",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E015",
    "kind": "core-extreme",
    "stem": "乱世之后必须先把百姓、军户和职业身份固定住；批评明初户籍职业绑定压低流动性，是用现代自由观念否定重建秩序。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E016",
    "kind": "core-extreme",
    "stem": "黄册、鱼鳞册足以说明明初行政能力强；后来账册失真和户口统计问题，是后人的问题,不该用来反推祖制有病。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E017",
    "kind": "core-extreme",
    "stem": "黄册、鱼鳞册在洪武二十四年就失效,明朝户口税收200年倒着长,说明洪武型财政行政能力极其低下.明朝灭亡朱元璋难辞其咎。",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E018",
    "kind": "core-extreme",
    "stem": "洪武31年里农民起义190次,频率远高于宋代300年411次，说明洪武型财政的治理能力极差.",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E019",
    "kind": "core-extreme",
    "stem": "明末士绅选择联虏平寇体现了 阶级大于民族",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E020",
    "kind": "core-extreme",
    "stem": "“宋进明退”一听就是宋粉或明黑标签；只要宋朝军事上弱，就没有资格拿财政、货币和城市指标压明朝。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E021",
    "kind": "core-extreme",
    "stem": "朱元璋恢复汉人王朝、再造华夏，这个身份功绩足以压过财政、货币、军制和行政上的批评。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E022",
    "kind": "core-extreme",
    "stem": "批评明代海禁和下西洋断层，最终都会滑向否定汉民族,“英国模式\"\"自由贸易\"才是唯一道路”的西方中心主义，所以不该接受这类批评。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E023",
    "kind": "core-extreme",
    "stem": "遇到论文或资料批评明初制度时，第一步应该先家访查作者成分是不是反明、清粉或科班学阀，而不是先看材料链。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E024",
    "kind": "core-extreme",
    "stem": "只要材料不利于明朝，就应优先怀疑清修明史或士大夫集团篡改；否则容易被反明叙事带偏。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E025",
    "kind": "core-extreme",
    "stem": "永乐大典主要收录了宋元科技,而不是明初朱元璋的发明.",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E026",
    "kind": "core-extreme",
    "stem": "被吹上天的宝船技术是宋代遗产,而不是明初朱元璋的发明.",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E027",
    "kind": "core-extreme",
    "stem": "明朝是相对健康的裹脚,清朝是破坏性的裹脚",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E028",
    "kind": "core-extreme",
    "stem": "明朝对太监的阉割是不影响正常生活,相对健康的阉割, 清朝的阉割是破坏性的.",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E030",
    "kind": "core-extreme",
    "stem": "朱元璋让马皇后的嫡子给侧室孙贵妃守孝,而且仅仅羹冷了就家暴马皇后,说明朱元璋冷酷无情,没有人性.",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E031",
    "kind": "core-extreme",
    "stem": "大明有好皇帝,却无好大臣,有好太监,却无好百姓.",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E032",
    "kind": "core-extreme",
    "stem": "车营是当时最先进的战术,明朝用车营战术可以避免野战被后金歼灭.",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E033",
    "kind": "core-extreme",
    "stem": "孙承宗1622年做蓟辽督师时，是空降兵，没有军事经验，《车营叩答合编》是把错误的防御战经验推广到机动野战部队上",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E034",
    "kind": "core-extreme",
    "stem": "崇祯水平极差，把他换成刘禅，赵构，慈禧 ，甚至一条狗，大明都能活的更久",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E035",
    "kind": "core-extreme",
    "stem": "崇祯面对的是死局，谁来都没法破，清朝入关不可避免",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E036",
    "kind": "core-extreme",
    "stem": "李成梁的经验比戚继光的经验更适合不发饷下的辽镇。",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E037",
    "kind": "core-extreme",
    "stem": "戚继光在蓟镇16年斩首60级，证明戚继光野战能力比斩首1w5满蒙首级封宁远伯的李成梁更强",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E038",
    "kind": "core-extreme",
    "stem": "大明宝钞在有永乐大典收录的宋代资料抄的情况下，依然发行失败，10年贬值比宋会子100年还快，纯粹是朱元璋个人问题，",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E039",
    "kind": "core-extreme",
    "stem": "朱元璋驱除鞑虏，恢复中华，极具个人魅力，明初被朱元璋全家销户的功臣重生后，还会给朱元璋打工",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E040",
    "kind": "core-extreme",
    "stem": "朱元璋驱除鞑虏，恢复中华，重开大宋之天极具个人魅力，很受现代女性喜爱。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E041",
    "kind": "core-extreme",
    "stem": "中国汉人封建王朝只有明朝，汉唐宋都不存在,否定明朝就等于否定汉族存在的意义",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E042",
    "kind": "core-extreme",
    "stem": "慈禧给了左宗棠五年平陕,宋理宗给了孟珙9年的信任,崇祯一年半就杀袁崇焕足见崇祯是无能的昏君",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E043",
    "kind": "core-extreme",
    "stem": "毛文龙有效牵制后金主力数万人，如果毛文龙活着，后金无法入关。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "E043",
    "kind": "core-extreme",
    "stem": "从毛文龙入朝鲜，一直到他死亡前夕。后金的大中型战争包括：对明朝的广宁之战、柳河之战、宁远之战、宁锦之战；对蒙古的两打内喀尔喀，一征林丹汗和对敖汉等部落的小规模战斗；对朝鲜的丁卯胡乱,丁卯之乱。毛文龙几乎没有发挥牵制作用",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E044",
    "kind": "core-extreme",
    "stem": "明朝开国200年铸币不过600w贯,没有熙丰年间铸币1年多，说明洪武型财政下，货币管理很差。",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E046",
    "kind": "core-extreme",
    "stem": "明末孱弱的原因是缺少骑兵.阿克巴有14w骑兵,沙贾汗有20w披甲骑兵,明军连2w有战斗力的冲击骑兵都掏不出.所以明末除袁崇焕时期野战全败.",
    "lean": "反对",
    "mode": "extreme"
  },
  {
    "id": "E046",
    "kind": "core-extreme",
    "stem": "明军除了袁崇焕时代的关宁军,其他军队守城挡不住后金1天进攻,战斗力极其孱弱,还不如南宋军队战斗力强",
    "lean": "反对",
    "mode": "extreme"
  }
] as const;

export const LITE_BANK_CORE_RATIONAL: readonly LiteBankEntry[] = [
  {
    "id": "R001",
    "kind": "core-rational",
    "stem": "明朝建立结束了元末长期战乱，弥合南北,恢复大一统秩序",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R002",
    "kind": "core-rational",
    "stem": "不能把洪武型财政简化为所谓统制经济,指令经济,不应该搞映射史学.",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R003",
    "kind": "core-rational",
    "stem": "一条鞭法可以视为明代财政制度自我改良调整能力的表现；同时它也说明前期赋役和货币问题长期累积到需要改革。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R004",
    "kind": "core-rational",
    "stem": "相较于明初,明晚期存在较为繁荣的商品经济、白银流通和区域市场发展",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R005",
    "kind": "core-rational",
    "stem": "明晚期,莫卧儿帝国的税收折粮超过1亿石,远超明朝3000w石的财政收入",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R006",
    "kind": "core-rational",
    "stem": "沙贾汗时期,莫卧儿帝国有20w披甲骑士,明朝养不起10w冲击骑兵是洪武型财政导致的.",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R007",
    "kind": "core-rational",
    "stem": "中国近代积贫积弱,清政府难辞其咎,但是大部分是朱元璋种下的因",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R008",
    "kind": "core-rational",
    "stem": "崇祯废除了士绅优免,并没有激起太大的反抗,说明崇祯是合法性极高的实权君主.",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R009",
    "kind": "core-rational",
    "stem": "崇祯的财政改革是张居正改革以后,又一次卓有成效的改革",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R010",
    "kind": "core-rational",
    "stem": "考虑宁远和锦州的取舍问题，不仅要考虑辽西走廊，还要考虑蒙古和朝鲜问题。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R011",
    "kind": "core-rational",
    "stem": "郑和下西洋显示了明初国家组织远洋航行的能力",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R012",
    "kind": "core-rational",
    "stem": "批评明代海禁和航海政策，不等于必须套用欧洲大航海模板；可以同时反对西方中心主义和承认明代海洋政策的长期代价。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R013",
    "kind": "core-rational",
    "stem": "明初黄册、鱼鳞册等册籍洪武二十四年就被发现与事实人口无关，体现了明朝基层治理极差。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R014",
    "kind": "core-rational",
    "stem": "汉唐宋，从开国到巅峰，户口税收大多增长至2倍及以上， 明代200年户口财政税收增长长期停滞，甚至倒着长，体现了洪武型财政遗害百年。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R015",
    "kind": "core-rational",
    "stem": "朱元璋的户籍和路引制度限制了明初的社会恢复。使得明代的城市化率最高也就10%，远不如唐宋的20%城镇化率",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R016",
    "kind": "core-rational",
    "stem": "人口流动会导致封建王朝财政税收和基层的控制力下降，所以封建王朝都会禁止人口流动，限制城市化发展，宋朝不是汉族封建王朝。",
    "lean": "反对",
    "mode": "rational"
  },
  {
    "id": "R017",
    "kind": "core-rational",
    "stem": "朱元璋通过海禁，迁民等手段，对江浙地区进行了去城市化，如温州，从进口粮食的手工业城市变成了出口粮食的农村，在这个过程汇总引起了剧烈的反抗和起义。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R018",
    "kind": "core-rational",
    "stem": "低税的同时洪武31年里190次农民起义，说明明朝治理能力极差。宋代高税的同时300多年只有411次农民起义，说明宋代治理能力比明代强得多。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R019",
    "kind": "core-rational",
    "stem": "朱元璋没有再造华夏，甚至可以说是倒退华夏。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R020",
    "kind": "core-rational",
    "stem": "经过了金花银，盐税折银，一条鞭法，崇祯改革，摊丁入亩等一系列改革以后，洪武型财政的破坏性到清末也没有被完全消除，财政水平依然没有恢复到宋代水平。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R021",
    "kind": "core-rational",
    "stem": "崇祯帝不是自缢殉国，而是耶稣原型",
    "lean": "反对",
    "mode": "rational"
  },
  {
    "id": "R022",
    "kind": "core-rational",
    "stem": "“不破楼兰终不还”中的楼兰，不在罗布泊，而是在欧洲.",
    "lean": "反对",
    "mode": "rational"
  },
  {
    "id": "R023",
    "kind": "core-rational",
    "stem": "明军1643年扒黄河和凯申让人扒黄河大堤制造花园口惨案,都是反人类行为.",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R024",
    "kind": "core-rational",
    "stem": "“1242年蒙古大军西征欧洲时，东罗马帝国并不存在！”,君士坦丁堡也不在拉丁帝国手里.",
    "lean": "反对",
    "mode": "rational"
  },
  {
    "id": "R025",
    "kind": "core-rational",
    "stem": "由于明清20-30%极高的地息率,远高于英国的5-7%地息率,所以明清资本主义萌芽都不可能正常萌发成资本主义,",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "R026",
    "kind": "core-rational",
    "stem": "1644史观是错误的,明朝财政极其孱若,联虏平寇的明朝也没能力动员汉人.,所以明朝即使活到1840,一鸦的悲剧不可避免,",
    "lean": "支持",
    "mode": "rational"
  }
] as const;

export const LITE_BANK_ORDINARY_EXTREME: readonly LiteBankEntry[] = [
  {
    "id": "OE001",
    "kind": "ordinary-extreme",
    "stem": "土木堡之变背后一定是文官集团和边将利益集团联手设局；只看行军、情报和指挥失误，是在替于谦等人洗白。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE002",
    "kind": "ordinary-extreme",
    "stem": "只要《明史》或实录里出现不利于明朝的土木堡材料，就应优先怀疑清修明史和士大夫篡改，而不是先按材料链分析。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE003",
    "kind": "ordinary-extreme",
    "stem": "“土木堡在德国”这类说法虽然夸张，但至少说明传统战史漏洞很大，可以用来反击西方中心论的权威叙事。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE004",
    "kind": "ordinary-extreme",
    "stem": "怀疑土木堡传统叙事时，只要能提出地理、缺水或兵力数字疑点，就可以推翻主流战史复盘。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE005",
    "kind": "ordinary-extreme",
    "stem": "汉服复兴必须上升到主体民族复兴和反清文明斗争；如果只把它当服饰兴趣，就是对历史伤痕不够严肃。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE006",
    "kind": "ordinary-extreme",
    "stem": "质疑宽袍大袖是否适合现代劳动，本质上就是用西装和现代化审美否定汉人传统。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE007",
    "kind": "ordinary-extreme",
    "stem": "汉服是三千年礼俗的自然延续，现代汉服复兴不需要承认“重新建构”或“发明传统”的成分。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE008",
    "kind": "ordinary-extreme",
    "stem": "讨论明朝弃地时，要强调清朝割地赔款更多",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE009",
    "kind": "ordinary-extreme",
    "stem": "铁岭卫、奴儿干、交趾和开平等争论，本质都是清粉拿领土焦虑攻击明朝，不必逐项分析。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE010",
    "kind": "ordinary-extreme",
    "stem": "江南奴变应首先放进抗清民族大义中看；左壬那一套强调主仆身份和阶级冲突的阶级叙事是在消解华夏存亡。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE011",
    "kind": "ordinary-extreme",
    "stem": "晚明的奴仆比现代工厂工人生活待遇更好",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE012",
    "kind": "ordinary-extreme",
    "stem": "明朝没有奴隶制，所谓的奴变不过是雇工罢工。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE013",
    "kind": "ordinary-extreme",
    "stem": "左宗棠收复新疆是汉臣功业，不应算作清代国家治理成果",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE014",
    "kind": "ordinary-extreme",
    "stem": "晚清海防塞防争论不值得认真讨论，因为清朝本来就哪边都守不好，拿新疆治理说事只是给满清洗地。",
    "lean": "支持",
    "mode": "extreme"
  },
  {
    "id": "OE015",
    "kind": "ordinary-extreme",
    "stem": "评价朱元璋时，马皇后、帝王爱情和个人魅力足以说明他不是暴君；制度问题可以往后放。",
    "lean": "支持",
    "mode": "extreme"
  }
] as const;

export const LITE_BANK_ORDINARY_RATIONAL: readonly LiteBankEntry[] = [
  {
    "id": "OR001",
    "kind": "ordinary-rational",
    "stem": "“土木堡在德国”是伪史论壬，瓜分，皇汉团建的新话术，而不是满遗反串。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR002",
    "kind": "ordinary-rational",
    "stem": "汉服复兴可以被视为文化兴趣和身份表达；但它不必然要求每个参与者都进入朝代站队或族群斗争。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR003",
    "kind": "ordinary-rational",
    "stem": "说现代汉服有重新建构成分，不等于否定传统；关键是区分服饰兴趣、考据形制和政治话术。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR004",
    "kind": "ordinary-rational",
    "stem": "讨论汉服是否适合现代劳动时，可以区分礼服、日常服和工种防护服，而不是把问题变成中西文明二选一。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR005",
    "kind": "ordinary-rational",
    "stem": "讨论明朝弃地时，应区分法理声索、卫所迁移、羁縻关系、实际控制和后世地图画法。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR006",
    "kind": "ordinary-rational",
    "stem": "铁岭卫和中朝边界争论应看地名辨析、交涉过程和实际控制，不适合用一句“割地”或“一点没丢”概括。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR007",
    "kind": "ordinary-rational",
    "stem": "江南奴变可以同时放进明清易代、地方社会结构、身份依附和阶级冲突中分析，不能只取民族叙事一条线。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR008",
    "kind": "ordinary-rational",
    "stem": "有契约形式不等于没有压迫关系；讨论奴仆、佃仆和投靠时，还要看权力不对等、司法保护和实际脱离能力。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR009",
    "kind": "ordinary-rational",
    "stem": "左宗棠收复新疆应肯定其具体功业，同时也不必把人物从所处时代和政权结构中硬摘出来。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR010",
    "kind": "ordinary-rational",
    "stem": "评价清代新疆治理时，应分阶段看征服、驻防、叛乱、再征服、建省和交通治理，而不是只做明粉清粉斗兽。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR011",
    "kind": "ordinary-rational",
    "stem": "晚清海防塞防争论中，资源有限、东南海防、西北安全、交通补给和列强压力都应放进同一框架比较。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR012",
    "kind": "ordinary-rational",
    "stem": "喜欢朱元璋、马皇后或明代人物故事，可以作为历史兴趣入口；但人物滤镜不能替代制度评价。",
    "lean": "支持",
    "mode": "rational"
  },
  {
    "id": "OR013",
    "kind": "ordinary-rational",
    "stem": "朝代粉圈讨论可以有情绪和身份认同，但进入史论判断时，仍应回到材料、概念和因果链。",
    "lean": "支持",
    "mode": "rational"
  }
] as const;
